[workspace]
members = ["lib", "benchmarks"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
ndarray = "0.15"
ndarray-rand = "0.14"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
