[package]
name = "machinelearne-rs"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
ndarray = { version = "0.16", optional = true }

[features]
default = ["cpu"]
cpu = []
ndarray = ["dep:ndarray"]
# tch = ["dep:tch"]
# burn = ["dep:burn"]
